hist <- read.csv("../data/first/sales_history.csv")
head(hist)
summary(hist)
unique(hist$日付)
aggregate(hist$日付, unique)
submission <- read.csv("../data/first/sample_submission.csv", header = F)
test <- read.csv("../data/first/test.csv")
head(test)
head(submission)
summary(submission)
summary(test)
