import pandas as pd

shop_1 = pd.DataFrame()
shop_2 = pd.DataFrame()
shop_3 = pd.DataFrame()
shop_4 = pd.DataFrame()
shop_5 = pd.DataFrame()
shop_6 = pd.DataFrame()
shop_7 = pd.DataFrame()
shop_8 = pd.DataFrame()
shop_9 = pd.DataFrame()
shop_10 = pd.DataFrame()
shop_11 = pd.DataFrame()
shop_12 = pd.DataFrame()
shop_13 = pd.DataFrame()
shop_14 = pd.DataFrame()
shop_15 = pd.DataFrame()
shop_16 = pd.DataFrame()
shop_17 = pd.DataFrame()
